name: "Purple Valley Coffee"
description: ""
author: "Cole Townsend"
email: cole@twnsnd.co
twitter: twnsndco
version: 2.1

future: true



images_url: /images/inline/
image:
  source: images/inline/

# Production
# ============================================================
exclude: ['README.md', '.gitignore', 'templates', 'node_modules', '.sublime-workspace', '.sublime-project', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
include:  ['.htaccess']

timezone:    America/New_York
future:      true
highlighter:    true
markdown: rdiscount
rdiscount:
  extensions:
    - smart
    - generate_toc

permalink: /:categories/:title

paginate: 4

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
